package labodeguita;

public class RTrabajadores extends javax.swing.JFrame {

    /**
     * Creates new form RTrabajadores
     */
    public RTrabajadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        txtfechanacimiento1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtnom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtape = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfechanacimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        listsexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btguardar = new javax.swing.JButton();
        btlimpiar = new javax.swing.JButton();
        btnuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtcemp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        listturno = new javax.swing.JComboBox<>();
        listcargo1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btsalir = new javax.swing.JButton();
        txtbusqueda = new javax.swing.JTextField();
        listcargo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Fecha de nacimiento");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de trabajadores");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos basicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(txtnom);
        txtnom.setBounds(10, 50, 119, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 30, 45, 15);
        jPanel1.add(txtape);
        txtape.setBounds(150, 50, 119, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Apellido");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 30, 44, 15);
        jPanel1.add(txtemail);
        txtemail.setBounds(10, 100, 119, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Correo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 80, 38, 15);
        jPanel1.add(txttelefono);
        txttelefono.setBounds(150, 100, 119, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Tel/Cel");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 80, 39, 15);
        jPanel1.add(txtfechanacimiento);
        txtfechanacimiento.setBounds(10, 160, 119, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Fecha de nacimiento");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 140, 115, 15);

        listsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "especifique genero...", "Hombre", "Mujer" }));
        jPanel1.add(listsexo);
        listsexo.setBounds(140, 160, 150, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Sexo");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 140, 27, 15);

        btguardar.setText("Guardar");
        jPanel1.add(btguardar);
        btguardar.setBounds(10, 210, 71, 23);

        btlimpiar.setText("Limpiar");
        jPanel1.add(btlimpiar);
        btlimpiar.setBounds(90, 210, 65, 23);

        btnuevo.setText("Nuevo");
        jPanel1.add(btnuevo);
        btnuevo.setBounds(160, 210, 63, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 70, 300, 280);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos basicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setLayout(null);
        jPanel2.add(txtcemp);
        txtcemp.setBounds(20, 50, 119, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("C.Empleado");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 30, 69, 15);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Cargo");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 230, 34, 15);
        jPanel2.add(txtuser);
        txtuser.setBounds(20, 150, 119, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Usuario");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 130, 44, 15);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Contraseña");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 180, 65, 15);
        jPanel2.add(txtpassword);
        txtpassword.setBounds(20, 200, 120, 20);

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(160, 10, 620, 250);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Turno");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 80, 32, 15);

        listturno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "elija su cargo...", "Matutino", "Vespertino", " ", " " }));
        jPanel2.add(listturno);
        listturno.setBounds(20, 100, 100, 20);

        listcargo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "elija su cargo...", "Cajero", "Almacen", "Gerente", "Administrador", " " }));
        jPanel2.add(listcargo1);
        listcargo1.setBounds(30, 250, 100, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(300, 70, 790, 280);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Registro de trabajadores");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(263, 11, 264, 29);

        btsalir.setText("Salir");
        jPanel3.add(btsalir);
        btsalir.setBounds(1044, 20, 36, 23);
        jPanel3.add(txtbusqueda);
        txtbusqueda.setBounds(772, 21, 239, 20);

        listcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tipo de busqueda...", "Codigo", "Telefono", "Nombre", "Apellido", " " }));
        jPanel3.add(listcargo);
        listcargo.setBounds(642, 21, 120, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 20, 1090, 50);

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));
        jPanel4.setLayout(null);
        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1090, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btguardar;
    private javax.swing.JButton btlimpiar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JButton btsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> listcargo;
    private javax.swing.JComboBox<String> listcargo1;
    private javax.swing.JComboBox<String> listsexo;
    private javax.swing.JComboBox<String> listturno;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtcemp;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfechanacimiento;
    private javax.swing.JTextField txtfechanacimiento1;
    private javax.swing.JTextField txtnom;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
