/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labodeguita;

/**
 *
 * @author sasuk
 */
public class VentaDeProductos extends javax.swing.JFrame {

    /**
     * Creates new form VentaDeProductos
     */
    public VentaDeProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(22, 22, 604, 213);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(512, 344, 100, 20);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(63, 306, 87, 20);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(63, 344, 87, 20);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(238, 344, 97, 20);

        jLabel1.setText("Cantidad");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(451, 347, 43, 14);

        jLabel2.setText("Precio");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(24, 309, 29, 14);

        jLabel3.setText("Fecha");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(24, 347, 29, 14);

        jLabel4.setText("Hora");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(205, 347, 23, 14);

        jTextField5.setToolTipText("buscar");
        jPanel2.add(jTextField5);
        jTextField5.setBounds(116, 268, 510, 20);

        jLabel5.setText("Nombre o descripcion");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 271, 102, 14);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(238, 306, 97, 20);

        jLabel6.setText("Total");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(204, 309, 24, 14);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(512, 306, 100, 20);

        jLabel7.setText("Codigo Producto");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(415, 309, 79, 14);

        jButton1.setText("Aceptar");
        jPanel2.add(jButton1);
        jButton1.setBounds(159, 402, 71, 23);

        jButton2.setText("Cancelar");
        jPanel2.add(jButton2);
        jButton2.setBounds(276, 402, 75, 23);

        jButton3.setText("Stock");
        jButton3.setToolTipText("Control De Productos");
        jPanel2.add(jButton3);
        jButton3.setBounds(399, 402, 59, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 70, 650, 450);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel8.setText("Venta De Productos");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 10, 353, 45);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaDeProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
