package labodeguita;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class VentaDeProductos extends javax.swing.JFrame {

    public VentaDeProductos() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrardatos("");
        
        nomFiado.setEnabled(false);
        ico1.setVisible(false);
        ico2.setVisible(false);
        //fecha local
        Calendar c;
        c=Calendar.getInstance();
        int d=c.get(Calendar.DATE), m=1+(c.get(Calendar.MONTH)), a=c.get(Calendar.YEAR);
        fecha.setText(a+"/"+m+"/"+d);
        
        Timer tiempo=new Timer(100, new VentaDeProductos.horas());
        tiempo.start();
        
        fiar(combo.getSelectedItem().toString());
    }
    
    class horas implements ActionListener{
    //hora local actualizable
        public void actionPerformed(ActionEvent e){
        Date sistHora=new Date();
        String pmAm="hh:mm:ss a";
        SimpleDateFormat format=new SimpleDateFormat(pmAm);
        Calendar hoy=Calendar.getInstance();
        hora.setText(String.format(format.format(sistHora),hoy));          
        }
    }
    
    public void fiar(String filtro)
    {
        if (filtro.equals("Pago")) 
        {
            nomFiado.setEnabled(false);
            ico2.setVisible(false);
            fiado.setEnabled(false);
            comprar.setEnabled(true);
        }
        if (filtro.equals("Fiado")) 
        {
            nomFiado.setEnabled(true);
            fiado.setEnabled(true);
            comprar.setEnabled(false);
        }
    }
    
    int cont=0;
    public void validar(){
        if (nomFiado.isEnabled()) {
            if(cant.getText().equals("")){ico1.setVisible(true);cont++;}              else{ico1.setVisible(false);}
            if(nomFiado.getText().equals("")){ico2.setVisible(true);cont++;}          else{ico2.setVisible(false);}
        }
        else {if(cant.getText().equals("")){ico1.setVisible(true);cont++;}              else{ico1.setVisible(false);}}
    }
    
    void limpiar(){
        nomFiado.setText("");
        pre.setText("");
        cant.setText("");
        total.setText("");
        cod.setText("");
        txtbuscar.setText("");
        nombre.setText("");
        desc.setText("");
        empre.setText("");
        stock.setText("");
        newStock.setText("");
    }
    
    void mostrardatos(String valor){
    DefaultTableModel modelo= new DefaultTableModel();
       modelo.addColumn("CODIGO");
       modelo.addColumn("NOMBRE");
       modelo.addColumn("DESCRIPCION");
       modelo.addColumn("EMPRESA");
       modelo.addColumn("PRECIO");
       modelo.addColumn("STOCK");
    tbdatos.setModel(modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT * FROM productos";
    }
    else{
        sql="SELECT * FROM productos WHERE cod_prod='"+valor+"'";
    }
 
    String []datos = new String [6];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString("cod_prod");
                datos[1]=rs.getString("nombre_prod");
                datos[2]=rs.getString("descripcion_prod");
                datos[3]=rs.getString("nomEmp");
                datos[4]=rs.getString("precio_prod");
                datos[5]=rs.getString("stock_prod");
                modelo.addRow(datos);
            }
            tbdatos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(ControlDeVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatos = new javax.swing.JTable();
        cant = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pre = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        cod = new javax.swing.JLabel();
        comprar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        nomFiado = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        empre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        newStock = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        ico1 = new javax.swing.JLabel();
        ico2 = new javax.swing.JLabel();
        fiado = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jMenuItem1.setText("Comprar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venta de productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel8.setText("Venta De Productos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbdatos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbdatos.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbdatos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 22, 820, 190));

        cant.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cant.setToolTipText("Enter para ver el total");
        cant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantKeyPressed(evt);
            }
        });
        jPanel2.add(cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 307, 90, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Cantidad");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 20));

        pre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 70, 20));

        txtbuscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtbuscar.setToolTipText("buscar");
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });
        jPanel2.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 460, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Busqueda por nombre o descripcion");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 20));

        total.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 90, 20));

        cod.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 70, 20));

        comprar.setText("Comprar");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });
        jPanel2.add(comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, 40));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, 40));

        jButton3.setText("Stock");
        jButton3.setToolTipText("Control De Productos");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, 40));

        combo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pago", "Fiado" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel2.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 170, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Nombre de la persona a fiar");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        nomFiado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel2.add(nomFiado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 170, -1));
        jPanel2.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 140, -1));
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 140, -1));
        jPanel2.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 140, -1));

        empre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        empre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empreActionPerformed(evt);
            }
        });
        jPanel2.add(empre, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 140, -1));

        jLabel3.setText("Stock");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, -1, -1));

        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, -1, -1));

        jLabel9.setText("Descripcion");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, -1, -1));

        jLabel10.setText("Empresa");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, -1, -1));
        jPanel2.add(newStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 140, -1));

        jLabel11.setText("Nuevo stock");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, -1, -1));

        hora.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 220, 20));

        fecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 220, 20));

        ico1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Braian Canjay\\Desktop\\DES AP 1\\32x32.png")); // NOI18N
        ico1.setToolTipText("Este campo no puede estar vacio");
        jPanel2.add(ico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 307, -1, 20));

        ico2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Braian Canjay\\Desktop\\DES AP 1\\32x32.png")); // NOI18N
        ico2.setToolTipText("Este campo no puede estar vacio");
        jPanel2.add(ico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, 20));

        fiado.setText("Fiar");
        fiado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiadoActionPerformed(evt);
            }
        });
        jPanel2.add(fiado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 60, 40));

        jLabel12.setText("Comprobador");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, -1, -1));

        jTextField1.setText("1");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 50, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setText("Precio");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Codigo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Total");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 860, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
       DefaultTableModel modelo= new DefaultTableModel();
       modelo.addColumn("CODIGO");
       modelo.addColumn("NOMBRE");
       modelo.addColumn("DESCRIPCION");
       modelo.addColumn("EMPRESA");
       modelo.addColumn("PRECIO");
       modelo.addColumn("STOCK");
       tbdatos.setModel(modelo);
       
       String consultar="SELECT * FROM productos WHERE nombre_prod LIKE '%"+txtbuscar.getText() + "%'"
               +"OR descripcion_prod LIKE '%"+txtbuscar.getText()+"%'";
       
       String []datos= new String[15];
        try {
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(consultar);
            while(rs.next())
            {
                datos[0]=rs.getString("cod_prod");
                datos[1]=rs.getString("nombre_prod");
                datos[2]=rs.getString("descripcion_prod");
                datos[3]=rs.getString("nomEmp");
                datos[4]=rs.getString("precio_prod");
                datos[5]=rs.getString("stock_prod");
                modelo.addRow(datos);
            }
            tbdatos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int cantidad,precio;
        int fila= tbdatos.getSelectedRow();
        if(fila>=0){
            cod.setText(tbdatos.getValueAt(fila, 0).toString());
            nombre.setText(tbdatos.getValueAt(fila, 1).toString());
            txtbuscar.setText(tbdatos.getValueAt(fila, 1).toString());
            desc.setText(tbdatos.getValueAt(fila, 2).toString());
            empre.setText(tbdatos.getValueAt(fila, 3).toString());
            pre.setText(tbdatos.getValueAt(fila, 4).toString());
            stock.setText(tbdatos.getValueAt(fila, 5).toString());
            newStock.setText(tbdatos.getValueAt(fila, 5).toString());
            
            cant.setText("1");
            cantidad = Integer.parseInt(cant.getText());
            precio = Integer.parseInt(pre.getText());
            total.setText(""+cantidad*precio);
            ico1.setVisible(false);
            ico2.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"no seleciono fila");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void empreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empreActionPerformed

    private void cantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantKeyPressed
        int cantidad,precio;    
        cantidad = Integer.parseInt(cant.getText());
        precio = Integer.parseInt(pre.getText());
        total.setText(""+cantidad*precio);
    }//GEN-LAST:event_cantKeyPressed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        //si total vacio seleccionar product, sino no
        int cantidad,stock1,nuevo;
        cont=0;
        validar();
        //si todos son invisibles hacer accion,si no mensaje de llenar campos
        if (ico1.isVisible()) {
            JOptionPane.showMessageDialog(null,"Llenó todos los campos?");
        }
        else{
            cantidad = Integer.parseInt(cant.getText());
            stock1 = Integer.parseInt(stock.getText());

            nuevo=stock1-cantidad;

            newStock.setText(""+nuevo);
            stock.setText(""+nuevo);

            try {
                PreparedStatement pstm = cn.prepareStatement("INSERT INTO ventas (nomVent, desVent, nomEmp, cantVent, preVent, totalVent, feVent, cod_prod, Nstock) VALUES (?,?,?,?,?,?,?,?,?)");
                pstm.setString(1, nombre.getText());
                pstm.setString(2, desc.getText());
                pstm.setString(3, empre.getText());
                pstm.setString(4, cant.getText());
                pstm.setString(5, pre.getText());
                pstm.setString(6, total.getText());
                pstm.setString(7, fecha.getText());
                pstm.setString(8, cod.getText());
                pstm.setString(9, stock.getText());
                pstm.executeUpdate();
                PreparedStatement pst2 = cn.prepareStatement("UPDATE productos SET stock_prod='"+newStock.getText()+"', nomEmp='"+empre.getText()+"', nombre_prod='"+nombre.getText()+"', descripcion_prod='"+desc.getText()+"',  precio_prod='"+pre.getText()+"' WHERE cod_prod='"+cod.getText()+"'");
                pst2.executeUpdate();
                mostrardatos("");
            }catch (Exception e) {
                System.out.print(e.getMessage());
            }
        }
        
            // TODO add your handling code here:
    }//GEN-LAST:event_comprarActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        fiar(combo.getSelectedItem().toString());
    }//GEN-LAST:event_comboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fiadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiadoActionPerformed
        // TODO add your handling code here:
        int cantidad,stock1,nuevo;
        cont=0;
        validar();
        //si todos son invisibles hacer update si no, mensaje de llenar campos
        if (ico1.isVisible() || ico2.isVisible()) {
            JOptionPane.showMessageDialog(null,"Llenó todos los campos?");
        }
        else{
            cantidad = Integer.parseInt(cant.getText());
            stock1 = Integer.parseInt(stock.getText());

            nuevo=stock1-cantidad;

            newStock.setText(""+nuevo);
            stock.setText(""+nuevo);

            try {
                PreparedStatement pst = cn.prepareStatement("INSERT INTO fiado(cliente, nomVent_f, desVent_f, nomEmp_f, cantVent_f, preVent_f, totalVent_f, feVent_F, cod_prod, Nstock) VALUES (?,?,?,?,?,?,?,?,?,?)");
                pst.setString(1, nomFiado.getText());
                pst.setString(2, nombre.getText());
                pst.setString(3, desc.getText());
                pst.setString(4, empre.getText());
                pst.setString(5, cant.getText());
                pst.setString(6, pre.getText());
                pst.setString(7, total.getText());
                pst.setString(8, fecha.getText());
                pst.setString(9, cod.getText());
                pst.setString(10, stock.getText());
                pst.executeUpdate();
                PreparedStatement pst2 = cn.prepareStatement("UPDATE productos SET stock_prod='"+newStock.getText()+"', nomEmp='"+empre.getText()+"', nombre_prod='"+nombre.getText()+"', descripcion_prod='"+desc.getText()+"',  precio_prod='"+pre.getText()+"' WHERE cod_prod='"+cod.getText()+"'");
                pst2.executeUpdate();
                mostrardatos("");
            } catch (Exception e) {
            System.out.print(e.getMessage());
            }
        }
    }//GEN-LAST:event_fiadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaDeProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cant;
    private javax.swing.JLabel cod;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton comprar;
    private javax.swing.JTextField desc;
    private javax.swing.JTextField empre;
    private javax.swing.JLabel fecha;
    private javax.swing.JButton fiado;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel ico1;
    private javax.swing.JLabel ico2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField newStock;
    private javax.swing.JTextField nomFiado;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel pre;
    private javax.swing.JTextField stock;
    private javax.swing.JTable tbdatos;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
LaBodeguita cc=new LaBodeguita();
Connection cn = cc.getConnection();
}